language: minimal
dist: focal
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: main

# Note that as of Sept 5, 2020 the TravisCI deploy provider "gcs" fails with "broken pipe" errors
# See https://github.com/travis-ci/travis-ci/issues/8100
# and https://github.com/travis-ci/dpl/pull/916
